spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    data:
      jpa:
        repositories:
          bootstrap-mode: default
logging:
  level:
    org:
      springframework: INFO
