server:
  port: 8443
  ssl:
    key-alias: tomcat
    key-store-password: tomcat
    key-store-type: PKCS12
    key-store: classpath:mykeystore.p12
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    data:
      jpa:
        repositories:
          bootstrap-mode: default
logging:
  level:
    org:
      springframework: INFO